return {
	{ id = 'RU_CAMO', displayName = "Russian Standard Camo", textureName = "Characters/Shared/ClothCamo/RU_Camo_01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'RU_DIGITAL', displayName = "Russian Digital Camo", textureName = "Characters/Shared/ClothCamo/RU_Digital_01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'RU_IZLOM', displayName = "Russian Izlom Camo", textureName = "Characters/Shared/ClothCamo/RU_Izlom", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'RU_IZOM', displayName = "Russian Izom Camo", textureName = "Characters/Shared/ClothCamo/RU_Izom", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'RU_PARTIZAN', displayName = "Russian Partizan Camo", textureName = "Characters/Shared/ClothCamo/RU_Partizan_01", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_Partizan" },
	{ id = 'RU_RASTR', displayName = "Russian Rastr Camo", textureName = "Characters/Shared/ClothCamo/RU_Rastr_01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'RU_SURPAT', displayName = "Russian Surpat Camo", textureName = "Characters/Shared/ClothCamo/RU_Surpat", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'RU_TIGER', displayName = "Russian Tiger Camo", textureName = "Characters/Shared/ClothCamo/RU_Tiger01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'RU_URBAN', displayName = "Russian Urban Camo", textureName = "Characters/Shared/ClothCamo/RU_Urban01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'RU_WOODLAND', displayName = "Russian Woodland Camo", textureName = "Characters/Shared/ClothCamo/RU_Woodland01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'RU_DIGIFLORA', displayName = "Russian DigiFlora Camo", textureName = "Characters/Shared/XP2_ClothCamo/DigiFlora", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_DigiFlora" },
	{ id = 'RU_KAMYSH', displayName = "Russian Kamysh Camo", textureName = "Characters/Shared/XP2_ClothCamo/Kamysh", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_Kamysh" },
	{ id = 'US_ACUPAT', displayName = "US ACUPAT Camo", textureName = "Characters/Shared/ClothCamo/US_ACUPAT", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'US_DESERT', displayName = "US Desert Camo", textureName = "Characters/Shared/ClothCamo/US_Desert_01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'US_MARPAT', displayName = "US MARPAT Camo", textureName = "Characters/Shared/ClothCamo/US_MARPAT_Desert", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'US_MARPAT_DESERT', displayName = "US MARPAT Desert Camo", textureName = "Characters/Shared/ClothCamo/US_MARPAT_Desert2", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'US_MARPAT_WOOD', displayName = "US MARPAT Wood", textureName = "Characters/Shared/ClothCamo/US_MARPAT_Wood", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'US_MITCHELL', displayName = "US Mitchell Camo", textureName = "Characters/Shared/ClothCamo/US_Mitchell", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'US_MULTICAM', displayName = "US Multicam Camo", textureName = "Characters/Shared/ClothCamo/US_Multicam3", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'US_UCP', displayName = "US UCP Camo", textureName = "Characters/Shared/ClothCamo/US_UCP", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'US_URBAN', displayName = "US Urban Camo", textureName = "Characters/Shared/ClothCamo/US_Urban01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'US_WOODLAN', displayName = "US Woodland Camo", textureName = "Characters/Shared/ClothCamo/US_Woodland", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'US_ABU', displayName = "US Airman Battle Uniform Camo", textureName = "Characters/Shared/XP2_ClothCamo/ABU", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_ABU" },
	{ id = 'US_DSRTTIGER', displayName = "DsrtTiger Camo", textureName = "Characters/Shared/XP2_ClothCamo/DsrtTiger", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_DesertTiger" },
	{ id = 'US_NWU', displayName = "Navy Working Uniform Camo", textureName = "Characters/Shared/XP2_ClothCamo/NWU", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_NWU" },
	{ id = 'UA_BERKUT', displayName = "Ukranian Berkut Camo", textureName = "Characters/Shared/XP2_ClothCamo/Berkut", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_Berkut" },
	{ id = 'ATACS', displayName = "A-TACS Camo", textureName = "Characters/Shared/XP2_ClothCamo/ATACS", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_ATACS" },

	{ id = 'BEIGE01', displayName = "Beige01 Color", textureName = "Characters/Shared/ColorSwatches/Beige01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREEN01', displayName = "Green01 Color", textureName = "Characters/shared/ColorSwatches/Green01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREEN02', displayName = "Green02 Color", textureName = "Characters/shared/ColorSwatches/Green02", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREEN03', displayName = "Green03 Color", textureName = "Characters/shared/ColorSwatches/Green03", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREEN06', displayName = "Green06 Color", textureName = "Characters/Shared/ColorSwatches/Green06", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREEN08', displayName = "Green08 Color", textureName = "Characters/Shared/ColorSwatches/Green08", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREEN09', displayName = "Green09 Color", textureName = "Characters/Shared/ColorSwatches/Green09", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREEN10', displayName = "Green10 Color", textureName = "Characters/Shared/ColorSwatches/Green10", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREENBLUE01', displayName = "GreenBlue01 Color", textureName = "Characters/Shared/ColorSwatches/GreenBlue01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREENBLUE02', displayName = "GreenBlue02 Color", textureName = "Characters/Shared/ColorSwatches/GreenBlue02", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREENBLUE03', displayName = "GreenBlue03 Color", textureName = "Characters/Shared/ColorSwatches/GreenBlue03", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'BLUE02', displayName = "Blue02 Color", textureName = "Characters/Shared/ColorSwatches/blue02", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'BLUE_JEANS01', displayName = "Blue_Jeans01 Color", textureName = "Characters/Shared/ColorSwatches/blue_Jeans01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'SAND01', displayName = "Sand01 Color", textureName = "Characters/shared/ColorSwatches/Sand01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'SAND02', displayName = "Sand02 Color", textureName = "Characters/shared/ColorSwatches/Sand02", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'SAND03', displayName = "Sand03 Color", textureName = "Characters/Shared/ColorSwatches/Sand03", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'SAND06', displayName = "Sand06 Color", textureName = "Characters/Shared/ColorSwatches/Sand06", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'SAND07', displayName = "Sand07 Color", textureName = "Characters/Shared/ColorSwatches/Sand07", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'SAND08', displayName = "Sand08 Color", textureName = "Characters/Shared/ColorSwatches/Sand08", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'BROWN02', displayName = "Brown02 Color", textureName = "Characters/Shared/ColorSwatches/brown02", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'BLACK01', displayName = "Black01 Color", textureName = "Characters/shared/ColorSwatches/black01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'BLACK04', displayName = "Black04 Color", textureName = "Characters/Shared/ColorSwatches/black04", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'PURE_BLACK', displayName = "Pure Black Color", textureName = "Characters/Shared/ColorSwatches/pure_black", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'WHITE', displayName = "White Color", textureName = "Characters/shared/ColorSwatches/white", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREY', displayName = "Grey Color", textureName = "Characters/Shared/ColorSwatches/Grey", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	{ id = 'GREY03', displayName = "Grey03 Color", textureName = "Characters/Shared/ColorSwatches/Grey03", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },	
}