return {
	RU_CAMO = { displayName = "Russian Standard Camo", textureName = "Characters/Shared/ClothCamo/RU_Camo_01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	RU_DIGITAL = { displayName = "Russian Digital Camo", textureName = "Characters/Shared/ClothCamo/RU_Digital_01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	RU_IZLOM = { displayName = "Russian Izlom Camo", textureName = "Characters/Shared/ClothCamo/RU_Izlom", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	RU_IZOM = { displayName = "Russian Izom Camo", textureName = "Characters/Shared/ClothCamo/RU_Izom", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	RU_PARTIZAN = { displayName = "Russian Partizan Camo", textureName = "Characters/Shared/ClothCamo/RU_Partizan_01", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_Partizan" },
	RU_RASTR = { displayName = "Russian Rastr Camo", textureName = "Characters/Shared/ClothCamo/RU_Rastr_01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	RU_SURPAT = { displayName = "Russian Surpat Camo", textureName = "Characters/Shared/ClothCamo/RU_Surpat", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	RU_TIGER = { displayName = "Russian Tiger Camo", textureName = "Characters/Shared/ClothCamo/RU_Tiger01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	RU_URBAN = { displayName = "Russian Urban Camo", textureName = "Characters/Shared/ClothCamo/RU_Urban01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	RU_WOODLAND = { displayName = "Russian Woodland Camo", textureName = "Characters/Shared/ClothCamo/RU_Woodland01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	RU_DIGIFLORA = { displayName = "Russian DigiFlora Camo", textureName = "Characters/Shared/XP2_ClothCamo/DigiFlora", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_DigiFlora" },
	RU_KAMYSH = { displayName = "Russian Kamysh Camo", textureName = "Characters/Shared/XP2_ClothCamo/Kamysh", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_Kamysh" },			
	US_ACUPAT = { displayName = "US ACUPAT Camo", textureName = "Characters/Shared/ClothCamo/US_ACUPAT", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	US_DESERT = { displayName = "US Desert Camo", textureName = "Characters/Shared/ClothCamo/US_Desert_01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	US_MARPAT = { displayName = "US MARPAT Camo", textureName = "Characters/Shared/ClothCamo/US_MARPAT_Desert", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	US_MARPAT_DESERT = { displayName = "US MARPAT Desert Camo", textureName = "Characters/Shared/ClothCamo/US_MARPAT_Desert2", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	US_MARPAT_WOOD = { displayName = "US MARPAT Wood", textureName = "Characters/Shared/ClothCamo/US_MARPAT_Wood", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	US_MITCHELL = { displayName = "US Mitchell Camo", textureName = "Characters/Shared/ClothCamo/US_Mitchell", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	US_MULTICAM = { displayName = "US Multicam Camo", textureName = "Characters/Shared/ClothCamo/US_Multicam3", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	US_UCP = { displayName = "US UCP Camo", textureName = "Characters/Shared/ClothCamo/US_UCP", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	US_URBAN = { displayName = "US Urban Camo", textureName = "Characters/Shared/ClothCamo/US_Urban01", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	US_WOODLAN = { displayName = "US Woodland Camo", textureName = "Characters/Shared/ClothCamo/US_Woodland", iconTexturePath = "UI/Art/Persistence/WeaponAccessory/NoSelection" },
	US_ABU = { displayName = "US Airman Battle Uniform Camo", textureName = "Characters/Shared/XP2_ClothCamo/ABU", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_ABU" },
	US_DSRTTIGER = { displayName = "DsrtTiger Camo", textureName = "Characters/Shared/XP2_ClothCamo/DsrtTiger", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_DesertTiger" },
	US_NWU = { displayName = "Navy Working Uniform Camo", textureName = "Characters/Shared/XP2_ClothCamo/NWU", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_NWU" },
	UA_BERKUT = { displayName = "Ukranian Berkut Camo", textureName = "Characters/Shared/XP2_ClothCamo/Berkut", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_Berkut" },
	ATACS = { displayName = "A-TACS Camo", textureName = "Characters/Shared/XP2_ClothCamo/ATACS", iconTexturePath = "UI/Art/Persistence/Specializations/Camo/PremiumCamo_ATACS" },	
}